### ISSUE TITLE
depends.txt is empty

### ISSUE THREAD

**Issue by farooghkz** [cheapie/rgblightstone#1]
This means that the mod does not depend on anything!

**Comment by cheapie** [comment]
That is correct. The mod does need digilines in order to work, but it doesn't have to be loaded first. The mod will also load and run without digilines, but it's not particularly useful that way.

**Comment by farooghkz** [comment]
So an idea: make the mod completely un-loadable without it's dependencies, it's much better i think, the use will know what to do.

**Comment by cheapie** [comment]
I don't think that's necessary since it's already listed in the readme.

**Comment by farooghkz** [comment]
not necessary but it's better, because mods are easier to use when all their dependencies are listed in depends.txt, even if the mod works without those mods, you should list them in depends.txt with a ?(=optional)
